#!/bin/bash
HOSTS="
    kuiper.lan.informatimago.com
    hubble.lan.informatimago.com
    galatea.lan.informatimago.com
    triton.lan.informatimago.com
    galle.lan.informatimago.com
    lassell.lan.informatimago.com
    voyager.informatimago.com
    neuron.intergruas.com
"

AHOSTS=
for h in $HOSTS ; do 
    ping -q -c 1 -w 4 $h >/dev/null 2>&1 \
    && AHOSTS="$AHOSTS $h"
done

quote(){
    for arg ; do
        local slash=${arg//\\/\\\\}
        local quote=\'${slash//\'/\'\\\'\'}\' # no "${...}" here! It would break the \'
        printf "%s " ${quote}
    done
    printf "\n"
}

args=$(quote "$@")

for h in $AHOSTS ; do
    printf "%-16s" ${h/\.*/} ; echo "ssh $h bash -c $(quote "$args")" ; ssh $h bash -c $(quote "$args")
done

#END#
