#!/bin/bash
exec xterm -bg green -fg black \
    +sb \
    -fn '-misc-fixed-medium-r-normal-*-*-140-75-*-*-*-iso8859-1' \
    -T atc \
    -e bash -c "while true ; do /usr/games/bin/atc -g ${1:-Atlantis} ; sleep 5 ; done"
exit 0

'-*-clean-bold-*-*-*-16-*-*-*-*-*-*-*' \

/usr/X11R6/bin/xterm +ah -aw -rw -cn -tn xterm-color -bc -bcf 200 -bcn 500 -bdc +cm +dc +mb -j +l -ls +nul -s -sb -si -sk -sl 14400 +t +vb -name xterm -sm +sp -fg #000000 -bg PowderBlue -T xt:pascal@naiad/sh -n xt:naiad

/usr/X11R6/bin/xterm +ah -aw -rw -cn -tn xterm-color -bc -bcf 200 -bcn 500 -bdc +cm +dc +mb -j +l -ls +nul -s -sb -si -sk -sl 14400 +t +vb -name xterm -sm +sp -fg #000000 -bg PowderBlue -T xt:pascal@naiad/sh -n xt:naiad
xterm +sb -bg green -fg black -fn -*-courier-bold-r-*-*-24-*-*-*-*-*-*-*

