#!/bin/bash

# Check if Caps Lock is on
caps_lock_state=$(xset q | grep "Caps Lock" | awk '{print $4}')

# If Caps Lock is on, simulate a Caps Lock key press to turn it off
if [ "$caps_lock_state" == "on" ]; then
    xdotool key Caps_Lock
fi
