#!/bin/bash
line="------------------------------------------------------------------------"
for f ; do
    p=$(echo "$f" | sed -e 's/././g')
    echo "$line"|sed -e "s/^\(....\).\(${p}\).\(.*\)/\1 ${f} \3/"
    cat $f
done
echo $line
#### cat-sources                      -- 2003-11-25 00:41:00 -- pascal   ####
