#!/bin/csh
cd /LocalApps
DockClock.app/DockClock --timeZoneName SanFrancisco --timeZoneMinutesEast -420&
sleep 3
DockClock.app/DockClock --timeZoneName NewYork      --timeZoneMinutesEast -240&
sleep 3
DockClock.app/DockClock --timeZoneName Bordeaux     --timeZoneMinutesEast  120&
sleep 3
DockClock.app/DockClock --timeZoneName Tokyo        --timeZoneMinutesEast  540&
sleep 3
DockClock.app/DockClock --timeZoneName Auckland     --timeZoneMinutesEast  720&
