#!/bin/sh 
(\
    echo ''                                                                        ;\
	echo '              local: '`                                            date` ;\
    echo ''                                                                        ;\
	echo 'San-Francisco (USA): '`TZ=/usr/share/zoneinfo/America/Los_Angeles  LC_TIME=en_US date` ;\
	echo 'New-York      (USA): '`TZ=/usr/share/zoneinfo/America/New_York     LC_TIME=en_US date` ;\
	echo 'London (Angleterre): '`TZ=/usr/share/zoneinfo/Europe/London        LC_TIME=en_UK date` ;\
	echo 'Paris      (France): '`TZ=/usr/share/zoneinfo/Europe/Paris         LC_TIME=fr_FR date` ;\
	echo 'Madrid    (Espagne): '`TZ=/usr/share/zoneinfo/Europe/Madrid        LC_TIME=es_ES date` ;\
	echo 'Riga     (Letonnie): '`TZ=/usr/share/zoneinfo/Europe/Riga          LC_TIME=lv_LV date` ;\
	echo 'Moscou     (Russie): '`TZ=/usr/share/zoneinfo/Europe/Moscow        LC_TIME=ru_RU date` ;\
	echo 'Tokyo       (Japon): '`TZ=/usr/share/zoneinfo/Asia/Tokyo           LC_TIME=ja_JP date` ;\
    echo ''                                                                         \
)|sed -e 's/\([^:]*:\) \([^ ][^ ]* [^ ][^ ]* [0-9][0-9]*\) \(.............\) *\([0-9]*\)$/\1 \3 \2 \4/'

