#!/bin/bash
#******************************************************************************
#FILE:               distribution
#LANGUAGE:           bash
#SYSTEM:             POSIX
#USER-INTERFACE:     POSIX
#DESCRIPTION
#    Identify the system, distribution and release where we run.
#    Prints a line with three corresponding keywords.
#    Status: 0 upon success.
#USAGE
#    distribution
#BUGS
#    We should add the processor to the output.
#AUTHORS
#    <PJB> Pascal J. Bourguignon <pjb@informatimago.com>
#MODIFICATIONS
#    2011-11-05 <PJB> Added support for MacOSX.
#    2001-04-29 <PJB> Creation.
#BUGS
#LEGAL
#	Copyright Pascal J. Bourguignon 2001 - 2010
#
#   This script is free software; you can redistribute it and/or
#   modify it under the terms of the GNU  General Public
#   License as published by the Free Software Foundation; either
#   version 2 of the License, or (at your option) any later version.
#
#   This script is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   General Public License for more details.
#
#   You should have received a copy of the GNU General Public
#   License along with this library; see the file COPYING.LIB.
#   If not, write to the Free Software Foundation,
#   59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#******************************************************************************

function distribution () {
    # DOES:   Identify the system, distribution and release where we run.
    #         Prints a line with three corresponding keywords.
    # STATUS: 0 upon success.
    
    
    # Sys-V systems have uname. It may also exist as an add-on on other systems.
    local systeme=
    local distrib="unknown"
    local release="unknown"
    systeme=$(uname -o) || systeme=$(uname) || systeme="unknown"


    case "$systeme" in

    Linux)
        if [ -e /etc/mandrake-release ] ; then
            distrib=mandrake
            release=$(awk '{print $4}' < /etc/mandrake-release)
            # Checked with Linux Mandrake 6.1

        elif [ -e /etc/redhat-release ] ; then
            distrib=redhat
            release=$(awk '{print $4}' < /etc/redhat-release)
            # Checked with Linux RedHat 6.1, 6.2, 7.0
            # Checked with Linux Immunix 6.2.
            # There seems to be no way to differenciate 
            # a RedHat 6.2 from an Immunix 6.2.
    
        elif [ -e /etc/conectiva-release ] ; then
            distrib=conectiva
            release=$(awk '{print $3}' < /etc/conectiva-release)
            # Checked with Linux Conectiva 6.5

        elif [ -e /etc/SuSE-release ] ; then
            distrib=SuSE
            release=$(grep VERSION /etc/SuSE-release|sed -e 's/.*= *//')
            # Checked with Linux SuSE 7.0, 7.1

        elif [ -e /etc/debian_version ] ; then
            distrib=debian
            release="$(cat /etc/debian_version)"
            # Checked with Linux DebIan 5.0.4

        elif [ -e /etc/gentoo-release ] ; then
            distrib=gentoo
            release=$(awk '{print $NF}' < /etc/gentoo-release)
            # Checked with Linux gentoo 1.12.9, 1.12.13

        else
            distrib=unknown
            release=unknown
        fi
        ;;

    NEXTSTEP)
        # A special case, where a uname has been installed on NeXTSTEP.
        distrib=NeXT
        release=$(uname -r) || release="unknown"
        ;;

    Darwin)
        release=$(hostinfo | awk '/Darwin Kernel Version/{printf "%s",substr($4,1,index($4,":")-1);}')
        if [ -r /System/Library/Frameworks/AppKit.framework/AppKit ] ; then
            distrib=apple
        fi
        # [pascal@localhost:/Users/pascal]$ hostinfo
        # Mach kernel version:
        #          Darwin Kernel Version 1.3.7:
        # Sat Jun  9 11:12:48 PDT 2001; root:xnu/xnu-124.13.obj~1/RELEASE_PPC
        # 
        # 
        # Kernel configured for up to 2 processors.
        # 1 processor is physically available.
        # Processor type: ppc7400 (PowerPC 7400)
        # Processor active: 0
        # Primary memory available: 1024.00 megabytes.
        # Default processor set: 54 tasks, 125 threads, 1 processors
        # Load average: 0.70, Mach factor: 0.74
        ;;
    unknown)

        # Mach systems:
        h=$(hostinfo) || h="unknown"

        case "$h" in 
        Mach*)
            # Well, this works on NeXTSTEP Mach:
            distrib=$(echo "$h" | awk '{print $4}')
            release=$(echo "$h" | awk '{print $6}')
            ;;
        *)
            ;;
        esac
        ;;

    *)
        release=$(uname  -r)
        ;;
    esac


    echo "$systeme" "$distrib" "$release"
} #distribution

distribution
exit 0

#### THE END ####
