#!/bin/bash

function emacsen         (){ 
    mkdir /tmp/emacs${UID}/ >/dev/null 2>&1 || true 
    chmod 700 /tmp/emacs${UID} 
    if [ -x /usr/local/bin/emacs ] 
    then EMACS=/usr/local/bin/emacs 
    else EMACS=emacs 
    fi 
    for EMACS_USE in pgm gnus erc 
    do EMACS_USE=$EMACS_USE $EMACS >/tmp/emacs${UID}/emacs-${EMACS_USE}.log 2>&1 & disown 
        sleep 17
    done 
}

emacsen
