#!/bin/bash
OPTIONS=(-nojoystick)
case "$1" in
-r|--record|record)
    date=$(date +%Y%m%dT%H%M%S) # 20100324T084801
    OPTIONS=( "${OPTIONS[@]}" -ao "pcm:file=/tmp/rc-${date}.wav" )
    ;;
esac

URL='mms://streaming.esradio.fm/EsRadio'
exec mplayer "${OPTIONS[@]}" "$URL"
########################################################################

# export WRITE_ASF=1
# POSITION=+512-0
# exec aviplay  -geometry $POSITION  $URL # /dev/null > /tmp/aviplay.log 2>&1

#### THE END ####

