#!/bin/bash
case "$1" in
[0-9]*) chapter="$1" ;;
*)      chapter=$(cat ~/.gatto-chapter) ;;
esac
tmp=/tmp/gatto-$$
trap "rm -rf $tmp" 0
mkdir "$tmp"
fic="$tmp/page"
for page in  a b c d e f g h i j k l m n o p q r s t u v w x y z ; do
    url="http://www.johntaylorgatto.com/chapters/${chapter}${page}.htm"
    lynx -dump "$url">"${fic}-${page}"
    if grep -q -s 'Error 404' "${fic}-${page}" ; then
        rm "${fic}-${page}"
    fi
done
cat "${fic}-"? >> "${fic}"
[ -s "${fic}" ] && cat "${fic}">>~/tmp/gatto.txt \
&& mail -s "[Gatto] Chapter ${chapter}" pascal<"${fic}" \
&& echo $(( $chapter + 1 )) > ~/.gatto-chapter
exit 0
#END#
