#!/bin/bash
DIR=$(get-directory CANCUN)
mkdir -p "$DIR"
cd       "$DIR"
wget -O `date '+%Y-%m-%d'`.jpg http://www.vialidad.telmex.net/fotos/f24.jpg \
|| ( sleep 60 ; wget -O `date '+%Y-%m-%d'`.jpg http://www.vialidad.telmex.net/fotos/f24.jpg ) \
|| ( sleep 60 ; wget -O `date '+%Y-%m-%d'`.jpg http://www.vialidad.telmex.net/fotos/f24.jpg )

