#!/bin/bash
# git config --global alias.clone-branches '! git branch -a | sed -n "/\/HEAD /d; /\/master$/d; /remotes/p;" | xargs -L1 git checkout -t'

git branch -a \
| sed -n "/\/HEAD /d; /\/master$/d; /remotes/p;" \
| cat

#| xargs -L1 git checkout -t
