#!/bin/sh

for f in /usr/man/man*/* ; do
case "$f" in
    *.bz2)
        bzip2 -d < $f | grep -q $@ && echo $f
        ;;
    *.gz)
        gzip -d  < $f | grep -q $@ && echo $f
        ;;
    *)
        cat      < $f | grep -q $@ && echo $f
        ;;
    esac
done
exit 0
