#!/bin/bash
pname=`basename "$0"`
dname=`dirname "$0"`

function usage () {
    echo "${pname} usage:"
    echo "    ${pname} file.html... > table-data"
}



function process () {
    currentFile="$1"
    echo ""
    echo "## FILE: ${currentFile}"
    cat $currentFile \
    | tr '\010\011\012\015'  '    '  \
    | sed -e 's/</ÿ</g' -e 's/>/>ÿ/g' \
    | tr 'ÿ' '\012' \
    | html-accents-to-isolatin1 \
    | tr '\240'  ' '  \
    | awk -f "$dname/html-get-tables.awk"
}

if [ $# -eq 0 ] ; then
    process /dev/stdin
else
    for arg ; do

        case "$arg" in
        --help)
            usage
            exit 0
            ;;
        -*)
            echo "${pname}: unknow option '${arg}'"
            usage
            exit 1
            ;;
        *)
            process "$arg"
            ;;
        esac
    done
fi
exit 0




