#!/usr/bin/perl

while(<>){
	s/&amp;/\&/g;
	s/&lt;/</g;
	s/&gt;/>/g;
	s/&Aacute;/Á/g;
	s/&Agrave;/À/g;
	s/&Acirc;/Â/g;
	s/&Atilde;/Ã/g;
	s/&Aring;/Å/g;
	s/&Auml;/Ä/g;
	s/&AElig;/Æ/g;
	s/&Ccedil;/Ç/g;
	s/&Eacute;/É/g;
	s/&Egrave;/È/g;
	s/&Ecirc;/Ê/g;
	s/&Euml;/Ë/g;
	s/&Iacute;/Í/g;
	s/&Igrave;/Ì/g;
	s/&Icirc;/Î/g;
	s/&Iuml;/Ï/g;
	s/&ETH;/Ğ/g;
	s/&Ntilde;/Ñ/g;
	s/&Oacute;/Ó/g;
	s/&Ograve;/Ò/g;
	s/&Ocirc;/Ô/g;
	s/&Otilde;/Õ/g;
	s/&Ouml;/Ö/g;
	s/&Oslash;/Ø/g;
	s/&Uacute;/Ú/g;
	s/&Ugrave;/Ù/g;
	s/&Ucirc;/Û/g;
	s/&Uuml;/Ü/g;
	s/&Yacute;/İ/g;
	s/&THORN;/Ş/g;
	s/&szlig;/ß/g;
	s/&aacute;/á/g;
	s/&agrave;/à/g;
	s/&acirc;/â/g;
	s/&atilde;/ã/g;
	s/&auml;/ä/g;
	s/&aelig;/æ/g;
	s/&ccedil;/ç/g;
	s/&eacute;/é/g;
	s/&egrave;/è/g;
	s/&ecirc;/ê/g;
	s/&euml;/ë/g;
	s/&iacute;/í/g;
	s/&igrave;/ì/g;
	s/&icirc;/î/g;
	s/&iuml;/ï/g;
	s/&eth;/ğ/g;
	s/&ntilde;/ñ/g;
	s/&oacute;/ó/g;
	s/&ograve;/ò/g;
	s/&ocirc;/ô/g;
	s/&otilde;/õ/g;
	s/&ouml;/ö/g;
	s/&oslash;/ø/g;
	s/&uacute;/ú/g;
	s/&ugrave;/ù/g;
	s/&ucirc;/û/g;
	s/&uuml;/ü/g;
	s/&yacute;/ı/g;
	s/&thorn;/ş/g;
	s/&yuml;/ÿ/g;

	s/&nbsp;/\240/g;

	s/&#161;/¡/g;   #Inverted exclamation
	s/&#162;/¢/g;   #Cent sign
	s/&#163;/£/g;   #Pound sterling
	s/&#164;/¤/g;   #General currency sign
	s/&#165;/¥/g;   #Yen sign
	s/&#166;/¦/g;   #Broken vertical bar
	s/&#167;/§/g;   #Section sign
	s/&#168;/˜/g;   #Umlaut (dieresis)
	s/&#169;/©/g;   #Copyright
	s/&#170;/ª/g;   #Feminine ordinal
	s/&#171;/«/g;   #Left angle quote, guillemotleft
	s/&#172;/¬/g;   #Not sign
	s/&#173;/­/g;   #Soft hyphen
	s/&#174;/®/g;   #Registered trademark
	s/&#175;/•/g;   #Macron accent
	s/&#176;/š/g;   #Degree sign
	s/&#177;/±/g;   #Plus or minus
	s/&#178;/²/g;   #Superscript two
	s/&#179;/³/g;   #Superscript three
	s/&#180;/’/g;   #Acute accent
	s/&#181;/µ/g;   #Micro sign
	s/&#182;/¶/g;   #Paragraph sign
	s/&#183;/·/g;   #Middle dot
	s/&#184;/›/g;   #Cedilla
	s/&#185;/¹/g;   #Superscript one
	s/&#186;/º/g;   #Masculine ordinal
	s/&#187;/»/g;   #Right angle quote, guillemotright
	s/&#188;/¼/g;   #Fraction one­fourth
	s/&#189;/½/g;   #Fraction one­half
	s/&#190;/¾/g;   #Fraction three­fourths
	s/&#191;/¿/g;   #Inverted question mark
	s/&#215;/×/g;   #Multiply sign
	s/&#247;/÷/g;   #Division sign

	s/<kbd>dotlessi<\/kbd>//g;
	s/&grave;/‘/g;
	s/&circ;/“/g;
	s/&tilde;/”/g;
	s/<kbd>breve<\/kbd>/–/g;
	s/<kbd>dotaccent<\/kbd>/—/g;
	s/<kbd>hungarumlaut<\/kbd>//g;
	s/<kbd>ogonek<\/kbd>//g;
	s/<kbd>caron<\/kbd>/Ÿ/g;
	s/<kbd>aring<\/kbd>/å/g;

	print;
}

