#!/bin/bash
# Fetch and install my environment.
# pjb@informatimago.com

# git config --global user.name "Pascal J. Bourguignon"
# git config --global user.email pjb@informatimago.com

# git repository to clone in ~/emacs
emacs_gitrepos=(
    git://github.com/remvee/android-mode.git
    git://github.com/capitaomorte/yasnippet.git
    git://github.com/emacs-java/auto-java-complete.git
    git://github.com/hayamiz/twittering-mode.git
)

# emacs lisp packages installed with elpa
elpackages=(
    auto-complete
    emms
    json
    popup
    w3m
)

system_packages=(
    clisp
    wget
    w3m
)


cd "$HOME"
[ -d bin ] || git clone ssh://pjb@git.informatimago.com/srv/git/public/bin bin
[ -d rc  ] || git clone ssh://pjb@git.informatimago.com/srv/git/public/rc  rc
make -C rc symlinks
source rc/bashrc



if [ -x /usr/local/bin/brew ] ; then
    if [ ! -x /usr/local/bin/clisp ] ; then
        brew install clisp
        sudo ln -s /usr/local/bin/clisp /usr/local/bin/clisp
    fi

    for sp in ${system_packages[@]} ; do
        if type -p "$sp" ; then
            true
        else
            brew install "$sp"
        fi
    done
fi


if [ ! -x /usr/local/bin/clisp -a -x /usr/local/bin/clisp ] ; then
    sudo ln -s /usr/local/bin/clisp /usr/local/bin/clisp
fi



mkdir -p src/public
cd src/public
[ -d lisp  ] || git clone ssh://pjb@git.informatimago.com/srv/git/public/lisp  lisp
[ -d emacs ] || git clone ssh://pjb@git.informatimago.com/srv/git/public/emacs emacs



cd "$HOME"
mkdir -p emacs
cd emacs

if [ ! -r subdirs.el ] ; then
    cat > subdirs.el <<EOF
(if (fboundp (quote normal-top-level-add-subdirs-to-load-path))
   (normal-top-level-add-subdirs-to-load-path))
EOF
fi

wget --mirror --no-directories --no-host-directories http://mumble.net/~campbell/emacs/paredit.el

# basename git://github.com/remvee/android-mode.git .git


function git-clone-or-pull(){
    local giturl="$1"
    local dir="$(basename "$1" .git)"
    if [ -d "$dir" ] ; then
        ( cd "$dir" ; git pull )
    else
        git clone "$giturl"
    fi
}

for repo in "${emacs_gitrepos[@]}" ; do
    git-clone-or-pull "$repo"
done


cd "$HOME"
if [ -x /Applications/Emacs.app/Contents/MacOS/Emacs ] ; then
    emacs=/Applications/Emacs.app/Contents/MacOS/Emacs
else
    emacs=emacs
fi
"$emacs"  --batch --eval "(dolist (package '(${elpackages[@]})) (package-install package))"

exit 0

    1  git clone ssh://pjb@git.informatimago.com/srv/git/public/rc/
    2  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
    5  cd /Applications/
   17  cd /Applications/Kindle.app/
   19  cd Contents/
   25  cd ../../TextWrangler.app/
   26  cd Contents/
   30  cd ../../ScreenshotMakerforiOS.app/
   31  cd Contents/
   34  cd
   35  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
   36  rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
   37  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
   38  brew doctor
   42  brew install git
   44  git clone ssh://pjb@git.informatimago.com/srv/git/public/rc/
   45  git clone ssh://pjb@git.informatimago.com/srv/git/public/bin
   46  cd rc
   52  brew install clisp
   53  brew install wget
   54  mkdir src/git
   55  mkdir -p src/git
   56  cd src/git
   58  git clone ssh://pjb@git.informatimago.com/srv/git/public/emacs
   59  git clone ssh://pjb@git.informatimago.com/srv/git/public/lisp
   60  cd ..
   61  ln -s git/* .
   63  mv git public
   68  git clone ssh://pjb@git.informatimago.com/srv/git/pjb/ubudu-stuff
   69  cd
   70  rsynch 192.168.1.151:~/quicklisp quicklisp
   71  rsynch 192.168.1.151:~/emacs emacs
