#!/bin/bash

# time=A  # Access
# time=C  # Change
time=T  # modificaTion

function lslast(){
	local args
	if [ "$#" -eq 0 ] ; then
		dirs=(.)
	else
		dirs=("$@")
	fi	
	find "${dirs[@]}" -printf "%${time}Y%${time}m%${time}dT%${time}T %p\n" \
	| sort -r \
	| head -20
}

lslast "$@"
