#!/bin/bash
case "$#" in
    0)
        interface=en1
        ;;
    1)
        case "$1" in
            -*) 
                
                "$0" help help
                ;;
            *)
                interface=$1 
                ;;
        esac
        ;;
    *)
        printf "%s usage:\n\n" "$(basename "$0")"
        printf "    %s [interface]\n\n" "$(basename "$0")"
        exit 64
        ;;
esac

sysctl -w net.inet.ip.forwarding=1
natd -interface ${interface} -dynamic
ipfw add divert natd all from any to any via ${interface}

exit 0
