#!/bin/bash
pname="$(basename "$0")"
server=hubble
umount=0
options=( -o nolockd  )

function usage(){
    printf "\n%s usage:\n    %s [unmount]\n\n" "$pname" "$pname" 
}

for arg ; do
case "$arg" in
-u|--umount|--unmount|umount|unmount) umount=1 ;;
-h|--help|help) usage ; exit 0 ;;
*)  printf "%s error: unknown option: %s\n" "$pname" "$arg" ; usage ; exit 1 ;;
esac
done

case "$(hostname)" in
macbook-pro-de-info-medicalis.local) mnt=/mnt/ ;;
*)                                   mnt=/     ;;
esac

if [ $umount -eq 1 ] ; then
    umount                ${server}:/mnt/sata/local/data
    umount                ${server}:/mnt/sata/local/home
    umount                ${server}:/mnt/sata/local/srv
    umount                ${server}:/mnt/sata/movies
else
    mount "${options[@]}" ${server}:/mnt/sata/local/data    ${mnt}data
    mount "${options[@]}" ${server}:/mnt/sata/local/home    ${mnt}home
    mount "${options[@]}" ${server}:/mnt/sata/local/srv     ${mnt}srv
    mount "${options[@]}" ${server}:/mnt/sata/movies        ${mnt}movies
fi
