#!/bin/bash
pname="$(basename "$0")"
server=kuiper.lan.informatimago.com
umount=0
options=( -o nolockd  )
hostname=$(hostname)
mnt=/mnt/

function usage(){
    printf "\n%s usage:\n    %s [unmount]\n\n" "$pname" "$pname" 
}

for arg ; do
    case "$arg" in
    -u|--umount|--unmount|umount|unmount) umount=1 ;;
    -h|--help|help) usage ; exit 0 ;;
    *)  printf "%s error: unknown option: %s\n" "$pname" "$arg" ; usage ; exit 1 ;;
    esac
done


if [ $umount -eq 1 ] ; then
    umount                ${mnt}data
    umount                ${mnt}home
    umount                ${mnt}srv
    case "${hostname}" in
    galatea)
        umount                ${mnt}movies
        ;;
    triton*)
        true
        ;;
    despina*)
        true
        ;;
    larissa*)
        true
        ;;
    *)
        true 
        ;;
    esac
else
    mount "${options[@]}" ${server}:/local/data    ${mnt}data
    mount "${options[@]}" ${server}:/local/home    ${mnt}home
    mount "${options[@]}" ${server}:/local/srv     ${mnt}srv
    case "${hostname}" in
    larissa*)
        mount "${options[@]}" ${server}:/movies    ${mnt}movies
        ;;
    galatea*)
        mount "${options[@]}" ${server}:/movies    ${mnt}movies
        ;; 
    triton*)
        true
        ;;
    despina*)
        true
        ;;
    *)
        true
        ;;
    esac
fi
