#!/bin/bash
set -eu
for file ; do
    echo "==== $file"
    case "$(file -L "$file")" in
        (*PEM\ certificate\ request*)
            openssl req -text -noout -verify -in "$file"
            ;;
        (*certificate*)
            openssl x509 -noout -text -in "$file" -inform pem
            ;;
        (*)
            openssl rsa  -noout -text -in "$file"
            ;;
    esac
done
