#!/bin/bash

function minutes(){
    local count="$1"
    printf $(( $count * 60 ))
}

PERIOD=$(minutes 10)
COOKIE=$(type -path fortune || type -path cookie || type -path /usr/local/bin/cookie)

#--
pname=$(basename "$0")

escape=''
bold="${escape}"'[1m'
underline="${escape}"'[4m'
blink="${escape}"'[5m'
invert="${escape}"'[7m'
no_bold="${escape}"'[22m'
no_underline="${escape}"'[24m'
no_blink="${escape}"'[25m'
no_invert="${escape}"'[27m'
black="${escape}"'[30m'
red="${escape}"'[31m'
green="${escape}"'[32m'
yellow="${escape}"'[33m'
blue="${escape}"'[34m'
magenta="${escape}"'[35m'
cyan="${escape}"'[36m'
white="${escape}"'[37m'
black_back="${escape}"'[40m'
red_back="${escape}"'[41m'
green_back="${escape}"'[42m'
yellow_back="${escape}"'[43m'
blue_back="${escape}"'[44m'
magenta_back="${escape}"'[45m'
cyan_back="${escape}"'[46m'
white_back="${escape}"'[47m'
normal="${escape}"'[0m'

function print_cookie(){
    local output="$1"
    local line=+-----------------------------------------------------------------------                
    local text="$("$COOKIE" 2>/dev/null)"
    if [ -n "$text" ] ; then
        {
            if ${COLOR_PROMPT:-false} ; then
                local back="${black_back}"
                local fore="${cyan}"
                local width=$(( ${COLUMNS:-80} - 3 ))
                printf '\n'
                printf '%s\n'   "$text" | \
                    while read line ; do
                        printf "%s%s %-${width}s %s \n" "${back}" "${fore}" "${line}" "${normal}" 
                    done
                printf '\n'
            else
                printf '\n%s\n' "$line"
                printf '%s\n'   "$text" | sed -e '/^$/d' -e 's/^/|  /' 
                printf '%s\n\n'  "$line"
            fi;
        } > $output
    fi
}

function print_usage(){
    
    cat <<EOF
${pname} usage:

    ${pname} [-i|--immediate] [-h|--help]

EOF
}

function period_cookie(){
    local immediate=false
    local output
    local period
    for arg in "$@" ; do
        case $arg in
        (-i|--immediate)
            immediate=true
            ;;
        (-h|--help)
            print_usage
            exit 0
            ;;
        -*)
            printf "Invalid option: %s\n" "$arg"
            print_usage
            exit 1
            ;;
        *)
            printf "Invalid argument: %s\n" "$arg"
            print_usage
            exit 1
            ;;
        esac
    done
    
    if [ "$(uname)" = Darwin ] ; then
        if [ -w /dev/tty ] ; then
            # From 10.4:
            output=/dev/tty
        else
            # Before 10.4:
            output=/dev/stdout
        fi
    else
        output=/dev/tty
    fi

    if $immediate ; then
        print_cookie "$output"
    elif [ -n "$COOKIE" ] ; then
        period=$PERIOD
        last=$(cat ~/.period-cookie 2>/dev/null)
        [ -z "$last" ] && last=0
        now=$(date +%s)
        if [ 0 -ne $(( now - last > period )) ] ; then
            echo "$now" > ~/.period-cookie
            print_cookie "$output"
        fi
    fi
}

period_cookie "$@"

#### THE END ####
