#!/bin/csh
#******************************************************************************
#FILE
#	quote
#DESCRIPTION
#	This filter script quotes each lines.
#AUTHORS
#	<PJB> Pascal J. Bourguignon
#MODIFICATIONS
#	1992/07/19 <PJB> Creation.
#LEGAL
#	Copyright Pascal J. Bourguignon 1992 - 1992
#	All rights reserved.
#******************************************************************************

set line="$<"
while ( "$line" != "" )
	echo \""$line"\"
	set line="$<"
end
