#!/bin/bash
URL="mms://a1830.l830120550.c8301.e.lm.akamaistream.net/D/1830/8301/v0001/reflector:20550"
OPTIONS=(-nojoystick)
exec mplayer "${OPTIONS[@]}" "$URL"

export WRITE_ASF=1
POSITION=+512-0
URL=/tmp/rne3.asx
cat>/tmp/rne3.asx<<EOF
<asx version="3.0">
	<title> RNE 3 </title>
	<author> rne.es </author>
<entry>
	<ref href="mms://a1830.l830120550.c8301.e.lm.akamaistream.net/D/1830/8301/v0001/reflector:20550"/>
	<ref href="mms://a1990.l830120551.c8301.e.lm.akamaistream.net/D/1990/8301/v0001/reflector:20551"/>
  </entry>
</asx>
EOF
exec aviplay  -geometry $POSITION  $URL  /dev/null > /tmp/aviplay.log 2>&1
#### radio-rne3                       --                     --          ####
