#!/bin/bash
URL="http://www.cope.es/cadena/directo.asx"
OPTIONS=(-nojoystick)
exec mplayer "${OPTIONS[@]}" "$URL"

POSITION=+512-0
export WRITE_ASF=1
exec aviplay  -geometry $POSITION  $URL  /dev/null > /tmp/aviplay.log 2>&1

