#!/bin/bash
OPTIONS=(-nojoystick)
DATE=$(date +%Y%m%dT%H%M%S) # 20100324T084801
NAME=radio
do_record=0


usage(){
    printf "%s [-r|--record] cadena-100 | cadena-cope | cope | courtoisie \\\\\n" "$0"
    printf "%s | deutchlandfunk | ie | news98 | rne3 | treffpunkt\n" "$(echo "$0"|sed -e 's/./ /g')"
}

if [ $# -eq 0 ] ; then
    usage
    exit 1
fi

for arg ; do
    case "$arg" in
    -r|--record)
        do_record=1
        ;;
    esradio)
        URL='mms://streaming.esradio.fm/EsRadio'
        NAME="$arg"
        ;;
    cadena-100)
        URL="http://www.cadena100.es/directo/directo.asx"
        NAME="$arg"
        ;;
    cadena-cope)
        URL="http://www.cope.es/cadena/directo.asx"
        NAME="$arg"
        ;;
    cope)
        URL="http://copefm.cope.stream.flumotion.com/cope/copefm.mp3.m3u"
        NAME="$arg"
        ;;
    courtoisie)
    # URL="http://mp3.live.tv-radio.com/courtoisie/all/courtoisie.mp3"
        URL="http://www.tv-radio.com/station/courtoisie/courtoisie.m3u"
        NAME="$arg"
        ;;
    deutchlandfunk)
        URL="http://dradio-live.mp3.t-bn.de/dlf_live"
        NAME="$arg"
        ;;
    ie)
        URL="mms://screamer.tippnet.ie/tmw"
        NAME="$arg"
        ;;
    news98)
        URL="http://himusic.aboutmedia.com.tw/ufo/ms-news98/asx/news98.asx"
        NAME="$arg"
        ;;
    rne3)
        URL="mms://a1830.l830120550.c8301.e.lm.akamaistream.net/D/1830/8301/v0001/reflector:20550"
        NAME="$arg"
        ;;
    treffpunkt)
        URL="http://www.cibersoft.com.ar/radio/radio.m3u"
        NAME="$arg"
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

if [ $do_record -ne 0 ] ; then
    OPTIONS=( "${OPTIONS[@]}" -ao "pcm:file=/tmp/${NAME}-${DATE}.wav" )
fi

exec mplayer "${OPTIONS[@]}" "$URL"

# POSITION=+512-0
# export WRITE_ASF=1
# exec aviplay  -geometry $POSITION  $URL  /dev/null > /tmp/aviplay.log 2>&1

