#!/bin/bash
URL="http://www.cibersoft.com.ar/radio/radio.m3u"
OPTIONS=(-nojoystick)
exec mplayer "${OPTIONS[@]}" "$URL"


POSITION=+512-0
exec realplayer $URL


#### radio-treffpunkt                 -- 2003-01-23 05:11:07 -- pascal   ####
