#!/bin/bash
pname="$(echo "$0"|sed -e 's/./ /g')"
OPTIONS=( -nojoystick -ontop )
DATE=$(date +%Y%m%dT%H%M%S) # 20100324T084801
NAME=radio
do_record=0

RADIOS=(
    tv-bfm
    nasatv
    esradio
    cadena-100
    cadena-cope
    cope
    reinfo
    courtoisie
    deutchlandfunk
    ie
    news98
    rne3
    treffpunkt
)

function usage(){
    printf '%s options... [station] \n\n' "$pname"
    printf 'Options are:\n\n'
    printf '    -r|--record          record the stream to a file /tmp/${RADIO_NAME}-${DATE}.wav\n'
    printf '    --bash-completions   prints the list of the defined radio stations.\'
    printf '\n'
}

if [ $# -eq 0 ] ; then
    usage
    exit 1
fi

function show(){
    for arg ; do
        printf '%20s = %s\n' "$arg" "$(eval "echo \$$arg")"
    done
}

function completion_all_stations(){
    for station in ${RADIOS[@]} ; do printf '%s\n' "$station" ; done
}

function completion_station_prefix(){
    local prefix="$1"
    for station in ${RADIOS[@]} ; do printf '%s\n' "$station" ; done | grep -e "^$prefix"
}

function find_previous_space(){
    local string="$1"
    local pos="$2"
    while [ $pos -ge 0 -a "${string:$pos:1}" != " " ] ; do
        pos=$(( $pos - 1 ))
    done
    echo $(( $pos + 1 ))
}

NAME="$arg"
for arg ; do
    case "$arg" in
    --bash-completion-function)
        echo 'function completion_radio(){ COMPREPLY=( $(radio --bash-completions "$COMP_CWORD" "${COMP_WORDS[@]}") ) ; } ; complete -F completion_radio  radio'
        exit 0
        ;;
    --bash-completions)
        shift
        index="$1"
        shift
        words=( "$@" )
        # show index '{words[@]}' '{words[$index]}' COMP_KEY COMP_LINE COMP_POINT COMP_TYPE COMP_WORDBREAKS 
        if [ "$COMP_KEY" = 9 ] ; then
            # TAB completion
            # inside COMP_LINE "$COMP_POINT"
            completion_all_stations
        elif [ -n "$index" ] ; then 
            # inside a word of ${COMP_WORD[@]}
            completion_station_prefix "${words[$index]}"
        else
            completion_all_stations
        fi
        exit 0
        ;;
    -r|--record)
        do_record=1
        ;;
    tv-bfm)
        URL="mms://vipmms9.yacast.net/bfm_bfmtv"
        ;;
    nasatv)
        asx(){
            tr '<>\015' '\012\012\012'< "$1" \
                | sed -n -e 's/.*[Rr][Ee][Ff]  *[Hh][Rr][Ee][Ff] *= *"\([^"]*\)".*/\1/p' \
                | head -1
        }
        trap 'rm -f /tmp/*-$$.nasatv' 0
        url='http://www.nasa.gov/55644main_NASATV_Windows.asx'
        wget "$url" -O "/tmp/1-$$.nasatv" > /dev/null 2>&1
        url2="$(asx /tmp/1-$$.nasatv)"
        wget "$url2" -O "/tmp/2-$$.nasatv" > /dev/null 2>&1
        URL="$(asx /tmp/2-$$.nasatv)"
        # OPTIONS=( "${OPTIONS[@]}" -vo gl:nomanyfmts )
        ;;
    esradio)
        URL='mms://streaming.esradio.fm/EsRadio'
        ;;
    cadena-100)
        URL="http://www.cadena100.es/directo/directo.asx"
        ;;
    cadena-cope)
        URL="http://www.cope.es/cadena/directo.asx"
        ;;
    cope)
        URL="http://copefm.cope.stream.flumotion.com/cope/copefm.mp3.m3u"
        ;;
    reinfo)
        URL="http://www.radiocourtoisie.net/tempo/public/reinfo/reinfo.mp3"
        ;;
    courtoisie)
    # URL="http://mp3.live.tv-radio.com/courtoisie/all/courtoisie.mp3"
        URL="http://www.tv-radio.com/station/courtoisie/courtoisie.m3u"
        ;;
    deutchlandfunk)
        URL="http://dradio-live.mp3.t-bn.de/dlf_live"
        ;;
    ie)
        URL="mms://screamer.tippnet.ie/tmw"
        ;;
    news98)
        URL="http://himusic.aboutmedia.com.tw/ufo/ms-news98/asx/news98.asx"
        ;;
    rne3)
        URL="mms://a1830.l830120550.c8301.e.lm.akamaistream.net/D/1830/8301/v0001/reflector:20550"
        ;;
    treffpunkt)
        URL="http://www.cibersoft.com.ar/radio/radio.m3u"
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done


if [ $do_record -ne 0 ] ; then
    OPTIONS=( "${OPTIONS[@]}" -ao "pcm:file=/tmp/${NAME}-${DATE}.wav" )
fi

exec mplayer "${OPTIONS[@]}" "$URL"

# POSITION=+512-0
# export WRITE_ASF=1
# exec aviplay  -geometry $POSITION  $URL  /dev/null > /tmp/aviplay.log 2>&1

