#!/bin/bash
URL="mms://screamer.tippnet.ie/tmw"
OPTIONS=(-nojoystick)
exec mplayer "${OPTIONS[@]}" "$URL"


POSITION=+512-0
export WRITE_ASF=1
exec aviplay  -geometry $POSITION  $URL  /dev/null > /tmp/aviplay.log 2>&1


exec aviplay mms://screamer.tippnet.ie/tmw
exec aviplay http://www.tippnet.ie/screaming/tmw.asx
aviplay http://www.cyberworld.ie/radio/Highland.asx

