#!/bin/csh -f

set files=()
set options=()

foreach arg ( $* )
	switch ( "$arg" )
	case -*:
		set options=($options "$arg")
		breaksw
	default:
		set files=($files "$arg")
		breaksw
	endsw
end

ident $files | sort -u \
| sed \
	-e 's/.*$Id: \([A-Za-z.,0-9]*\) \([0-9.]*\) .*/co '"$options"' -r\2 RCS\/\1/' \
	> /tmp/rcscoident.$$
source /tmp/rcscoident.$$
#END
