#!/bin/csh -f -b
#***ID-DEBUT***********************************************************
#NOM:    	rcslinklog
#LANGAGE:	/bin/csh
#SYSTEME:	UNIX
#TYPE:   	COMMANDE
#DESCRIPTION:
#	Copie les arguments dans un journal.
#UTILISATION:
#	rcslinklog argument ...
#AUTEURS:
#	PBO	Pascal Bourguignon	DSI/EI/MH/OPP
#MODIFICATIONS:
#	$Id$
#	$Log$
#	1994/MM/JJ [PROJET/TACHE] PBO Creation.
#BOGUES:
#LEGAL:
#	Copyright ABEILLE VIE, 1994
#***ID-FIN*************************************************************
		
	
	echo "$argv" >> /dvptop/general/RCS/.linklog

	exit 0
#END rcslinklog.
