#!/bin/csh -f -b
#***ID-DEBUT***********************************************************
#NOM:    	rcslinkopp
#LANGAGE:	/bin/csh
#SYSTEME:	UNIX
#TYPE:   	COMMANDE
#DESCRIPTION:
#	Encapsule la commande rcslink pour les repertoires d'application 
#	OpenPrint.
#UTILISATION:
#	rcslinkopp appliopp
#AUTEURS:
#	PBO	Pascal Bourguignon	DSI/EI/MH/OPP
#MODIFICATIONS:
#	1994/07/08 [OPP/META01_PGM] PBO Creation.
#BOGUES:
#LEGAL:
#	Copyright ABEILLE VIE, 1994
#***ID-FIN*************************************************************
	
	if ( $#argv == 1 ) then
		echo "${0:t} usage :"
		echo "	${0:t} application_openprint ..."
		exit 1
	endif
	foreach app ( $* )
		set opEnv=/dvptop
		set opInstallDir=/openprint
		set opWD=$opEnv/$app		
		cd $opWD && rcslink -c -v $app macro program record text
	end
	exit 0
#END rcslinkopp.
