#!/bin/sh

cat /usr/X11/lib/X11/rgb.txt | while read r g b name remainder ; do
	if expr "$r" ":" "!.*" ; then
		echo ''
	else
		if [ -z "$remainder" ] ; then
			xsetroot -solid $name
			echo ''
			echo $name
			sleep 3
		fi
	fi
done
