#!/bin/bash
host="$1"
pname="$(basename "$0")"
if [ "$host" = "" ] ; then
   echo "$pname usage:"
   echo "    $pname HOST"
   exit 0
fi
ssh-keygen -f ~/.ssh/known_hosts -R "$host" || sed -i -e "/$host/d" ~/.ssh/known_hosts
