#!/bin/bash
mkdir ~/News/suck.d ~/News/suck.m ~/News/suck.t 2>/dev/null|| true
suck \
    -dd ~/News/suck.d \
    -dm ~/News/suck.m \
    -dt ~/News/suck.t \
    -f -F \
    -m \
    news.easynet.fr

    

#### sux                              -- 2003-11-30 00:08:08 -- pascal   ####
