#!/bin/bash -e
cd "$HOME"

destination=larissa
larissa=larissa.local

despina_dirs=( firms persons private quicklisp src src-lisp works )
larissa_dirs=( firms         private quicklisp src src-lisp works )


rsync_options=(-HSWavxE --perms -pogt --progress --force --delete --delete-during --rsh='ssh -x' -z)

eval 'dirs=("${'"${destination}_dirs"'[@]}")'
for dir in ${dirs[@]} ; do
    printf "==================== %s\n" "$dir"
    time rsync "${rsync_options[@]}"   "${dir}/" "${!destination}:${dir}"
done
