#!/bin/bash
trap 'rm -f /tmp/$$.url'  EXIT

nc termbin.com 9999 | tr -d '\000' > /tmp/$$.url
type -p xclip  >/dev/null && xclip -i < /tmp/$$.url
type -p pbcopy >/dev/null && pbcopy   < /tmp/$$.url
cat /tmp/$$.url

