#!/bin/csh -f 
echo 'See emacs M-x pjb-update-copyright'
exit 0

set year=`date |sed -e 's/.* \([0-9][0-9][0-9][0-9]\)$/\1/'`
foreach f ( ${*:q} )
	echo Updating \'${f:q}\'..
	cp ${f:q} ${f:q}~
	sed -e 's/Copyright\(.Bourguignon.*\)[12][0-9][0-9][0-9] *$/Copyright\1'${year:q}'/' \
		< ${f:q}~ >! ${f:q}
	grep Copyright ${f:q}
end

exit 0
