#!/bin/bash
xset -dpms
xsetroot -solid '#137'

setxkbmap us -option ctrl:ac_ctrl
xkbset nullify lock
# xdotool key  Caps_Lock
# xte "key Caps_Lock"

case "$(hostname)" in
(minint|*span)
    xrandr --size 1680x1050
    gsettings set org.freedesktop.ibus.general.hotkey triggers []
    xterm -fg green -bg black -fn terminus-32  -e screen    & disown
    emacs & disown
    (sleep 30 ; thunderbird >/tmp/thunderbird-${UID}-$$.log & disown) &
    (sleep 50 ; firefox     >/tmp/firefox-${UID}-$$.log     & disown) &
    ;;
(*)
    pjb-xterm green -e screen & disown
    (sleep 10 ; emacsen ) & disown
    (sleep 50 ; firefox >/tmp/firefox-${UID}-$$.log & disown) &
    ;;
esac
